version: '3.8'

services:
  api:
    image: medsync/api:${VERSION}
    build:
      context: backend
      dockerfile: Dockerfile
  db:
    image: medsync/db:${VERSION}
    build:
      context: medsync-db
      dockerfile: Dockerfile
  worker:
    image: medsync/worker:${VERSION}
    build:
      context: worker
      dockerfile: Dockerfile
