version: '3.8'

services:
  api:
    image: medsync/api:${VERSION}
    container_name: medsync-api
    restart: unless-stopped
    command: sh -c "python -m flask run --host=0.0.0.0 --port=${APPLICATION_PORT}"
    volumes:
      - ./medsync-api:/app
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=${FLASK_APP}
      - PYTHONPATH=src
      - DATABASE_URL=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
      - APPLICATION_PORT=${APPLICATION_PORT}
      - APPLICATION_SECRET=${APPLICATION_SECRET}
      - APPLICATION_HOST=${APPLICATION_HOST}
      - APPLICATION_DB_CONTAINER_NAME=db

  db:
    image: medsync/db:${VERSION}
    container_name: medsync-db
    restart: unless-stopped
    volumes:
      - medsync-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  temporal:
    image:  medsync/temporal:${VERSION}
    container_name: medsync-temporal
    restart: unless-stopped
    ports:
      - "7233:7233"
    environment:
      - DB=postgresql
      - DB_PORT=${POSTGRES_PORT}
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml
      - LOG_LEVEL=debug
      - POSTGRES_PWD=${POSTGRES_PASSWORD}
      - POSTGRES_SEEDS=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - ./medsync-temporal/config:/etc/temporal/config/dynamicconfig

  temporal-ui:
    image: temporalio/ui:2.22.3
    container_name: medsync-temporal-ui
    restart: unless-stopped
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGIN=http://localhost:3000
    ports:
      - "8080:8080"
volumes:
  medsync-db:
