version: '3.8'

services:
  api:
    image: medsync/api:${VERSION}
    build:
      context: medsync-api
      dockerfile: Dockerfile
    container_name: medsync-api
    restart: unless-stopped
    command: sh -c "python -m flask run --host=0.0.0.0 --port=${APPLICATION_PORT}"
    volumes:
      - ./medsync-api:/app
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=${FLASK_APP}
      - PYTHONPATH=src
      - DATABASE_URL=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
      - APPLICATION_PORT=${APPLICATION_PORT}
      - APPLICATION_SECRET=${APPLICATION_SECRET}
      - APPLICATION_HOST=${APPLICATION_HOST}
      - APPLICATION_DB_CONTAINER_NAME=db

  db:
    image: medsync/db:${VERSION}
    build:
      context: medsync-db
      dockerfile: Dockerfile
    container_name: medsync-db
    restart: unless-stopped
    volumes:
      - medsync-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  
  temporal:
    image: medsync/temporal:${VERSION}
    build: 
      context: medsync-temporal
      dockerfile: Dockerfile
    container_name: medsync-temporal

volumes:
  medsync-db:
