version: '3.8'

services:
  api:
    image: medsync/api:${VERSION}
    build:
      context: medsync-api
      dockerfile: Dockerfile
    container_name: medsync-api
    restart: unless-stopped
    ports:
      - "5000:5000"
  db:
    image: medsync/db:${VERSION}
    build:
      context: medsync-db
      dockerfile: Dockerfile
    container_name: medsync-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - CONFIG_DATABASE_PASSWORD=${CONFIG_DATABASE_PASSWORD:-}
      - CONFIG_DATABASE_URL=${CONFIG_DATABASE_URL:-}
      - CONFIG_DATABASE_USER=${CONFIG_DATABASE_USER:-}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
    