services:
#   api:
#     container_name: medsync-api
#     build:
#       context: medsync-api
#       dockerfile: Dockerfile
#     command: pnpm run start
#     ports:
#       - 5000:5000
#     environment:
#       - PORT=5000
#       - NODE_ENV=development
#       - DATABASE_URL=postgresql://postgres:secret@db:5432/api?schema=public
#       - JWT_SECRET=thisisasamplesecret
#       - JWT_ACCESS_EXPIRATION_MINUTES=30
#       - JWT_REFRESH_EXPIRATION_DAYS=30
#       - JWT_RESET_PASSWORD_EXPIRATION_MINUTES=10
#       - JWT_VERIFY_EMAIL_EXPIRATION_MINUTES=10
#       - SMTP_HOST=email-server
#       - SMTP_PORT=587
#       - SMTP_USERNAME=email-server-username
#       - SMTP_PASSWORD=email-server-password
#       - NEOSYNC_API_URL=http://engine:8080
# 
#       - AUTH_ENABLED=false
#       - AUTH_ISSUER=http://keycloak:8080/realms/neosync
#       - AUTH_EXPECTED_ISSUER=http://localhost:8083/realms/neosync
#       - AUTH_AUTHORIZE_URL=http://localhost:8083/realms/neosync/protocol/openid-connect/auth
#       - AUTH_USERINFO_URL=http://keycloak:8080/realms/neosync/protocol/openid-connect/userinfo
#       - AUTH_TOKEN_URL=http://keycloak:8080/realms/neosync/protocol/openid-connect/token
# 
#       - AUTH_CLIENT_ID=neosync-app
#       - AUTH_CLIENT_SECRET=72alWGzhHInDskRHduTQ8BjB4Lgn0n3a
#       - AUTH_AUDIENCE=neosync
#       - AUTH_SCOPE=openid email profile offline_access
#       - AUTH_PROVIDER_ID=keycloak
#       - AUTH_PROVIDER_NAME=Keycloak
#     networks:
#       - medsync-network
#       - kc-network
#     depends_on:
#       - db
#       - engine
#       - worker

  engine:
    container_name: medsync-engine
    image: ghcr.io/nucleuscloud/neosync/api
    # network_mode: host
    ports:
      - 8080:8080
    command: serve connect
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - NUCLEUS_ENV=dev
      - TEMPORAL_URL=temporal:7233
      - DB_AUTO_MIGRATE=true
      - DB_SCHEMA_DIR=/migrations
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=neosync
      - DB_USER=postgres
      - DB_PASS=secret
      - DB_SSL_DISABLE=true
      - DB_MIGRATIONS_TABLE=neosync_api_schema_migrations
      - DB_MIGRATIONS_TABLE_QUOTED=false
      - AUTH_ENABLED=true
      - AUTH_AUDIENCE=neosync
      - AUTH_BASEURL=http://keycloak:8080/realms/neosync
      - AUTH_EXPECTED_ISS=http://localhost:8083/realms/neosync
      - AUTH_CLI_CLIENT_ID=neosync-cli
      - AUTH_CLI_AUDIENCE=neosync
      - AUTH_CLIENTID_SECRET={"neosync-cli":"GkVsthDzDvBfzb2vT4UO95xbXrwoXE5w"}
      - AUTH_SIGNATURE_ALGORITHM=RS256
    networks:
      - medsync-network
      - temporal-network
      - kc-network
    restart: on-failure
    depends_on:
      - db
  db:
    container_name: medsync-db
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_MULTIPLE_DATABASES=api,neosync
    networks:
      - medsync-network
      - kc-network
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./medsync-db:/docker-entrypoint-initdb.d

  worker:
    container_name: medsync-worker
    image: ghcr.io/nucleuscloud/neosync/worker
    # network_mode: host
    environment:
      - NUCLEUS_ENV=dev
      - TEMPORAL_URL=temporal:7233
      - TEMPORAL_NAMESPACE=default
      - TEMPORAL_TASK_QUEUE=sync-job
      - NEOSYNC_URL=http://engine:8080
      - REDIS_URL=redis://default:foofar@redis:6379
    networks:
      - medsync-network
      - temporal-network
    restart: on-failure

  redis:
    container_name: medsync-redis
    image: redis:7.2.4
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass foofar
    networks:
      - medsync-network
    volumes:
      - redis_cache:/data

  keycloak:
    container_name: medsync-auth-keycloak
    image: quay.io/keycloak/keycloak
    ports:
      - 8083:8080
    command: start-dev --import-realm
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=password

      - KC_HOSTNAME_URL=http://116.193.191.197:8083
      - KC_PROXY_HEADER=forwarded
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HTTP_ENABLED=true

      - KC_DB=postgres
      - KC_DB_URL_HOST=db
      - KC_DB_URL_PORT=5432
      - KC_DB_URL_DATABASE=neosync
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=secret
      - KC_DB_SCHEMA=keycloak
    volumes:
      - ./keycloak/imports:/opt/keycloak/data/import
    networks:
      - kc-network
    depends_on:
      - db
volumes:
  redis_cache:
  pg_data:
networks:
  medsync-network:
    driver: bridge
    name: medsync-network
  temporal-network:
    external: true
  kc-network:
    driver: bridge
    name: kc-network
