version: '3.8'

services:
  api:
    container_name: medsync-api
    image: medsync-api
    build:
      context: ./backend
      dockerfile: ./dev/build/Dockerfile.dev
    ports:
      - 8080:8080
    command: serve connect
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - NUCLEUS_ENV=dev
      - TEMPORAL_URL=temporal:7233
      - DB_AUTO_MIGRATE=true
      - DB_SCHEMA_DIR=/app/migrations
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASS=${POSTGRES_PASSWORD}
      - DB_SSL_DISABLE=true
      - DB_MIGRATIONS_TABLE=neosync_api_schema_migrations
      - DB_MIGRATIONS_TABLE_QUOTED=false
      - AUTH_ENABLED=false

    networks:
      - medsync-network
      - temporal-network
    depends_on:
      - db
    restart: on-failure

  db:
    image: postgres:13
    container_name: medsync-db
    restart: unless-stopped
    networks:
      - medsync-network
    volumes:
      - ./medsync-db:/docker-entrypoint-initdb.d
      - medsync-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  worker:
    container_name: medsync-worker
    image: medsync-worker
    build:
      context: worker
      dockerfile: Dockerfile
    environment:
      - NUCLEUS_ENV=dev
      - TEMPORAL_URL=temporal:7233
      - TEMPORAL_NAMESPACE=default
      - TEMPORAL_TASK_QUEUE=sync-job
      - NEOSYNC_URL=http://api:8080
      - REDIS_URL=redis://default:${REDIS_PASSWORD}@redis:6379
      - LOG_LEVEL=INFO
    networks:
      - medsync-network
      - temporal-network
    restart: on-failure

  redis:
    container_name: medsync-redis
    image: redis:7.2.4
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - medsync-redis:/data
    networks:
      - medsync-network

volumes:
  medsync-db:
  medsync-redis:
networks:
  medsync-network:
    driver: bridge
    name: medsync-network
  temporal-network:
    external: true
