version: '3.8'

services:
  api:
    image: medsync/api:${VERSION}
    build:
      context: medsync-api
      dockerfile: Dockerfile
  db:
    image: medsync/db:${VERSION}
    build:
      context: medsync-db
      dockerfile: Dockerfile
  temporal:
    image: medsync/temporal:${VERSION}
    build:
      context: medsync-temporal
      dockerfile: Dockerfile
        
    