// import { JsonValue } from '@bufbuild/protobuf';
// import { GetSystemTransformersResponse } from '@neosync/sdk';
import { HookReply } from './types';
import { useAuthenticatedFetch } from './useAuthenticatedFetch';
// import { useNucleusAuthenticatedFetch } from './useNucleusAuthenticatedFetch';


export enum TransformerSource {
  TRANSFORMER_SOURCE_UNSPECIFIED = 0,
  TRANSFORMER_SOURCE_PASSTHROUGH = 1,
  TRANSFORMER_SOURCE_GENERATE_DEFAULT = 2,
  TRANSFORMER_SOURCE_TRANSFORM_JAVASCRIPT = 3,
  TRANSFORMER_SOURCE_GENERATE_EMAIL = 4,
  TRANSFORMER_SOURCE_TRANSFORM_EMAIL = 5,
  TRANSFORMER_SOURCE_GENERATE_BOOL = 6,
  TRANSFORMER_SOURCE_GENERATE_CARD_NUMBER = 7,
  TRANSFORMER_SOURCE_GENERATE_CITY = 8,
  TRANSFORMER_SOURCE_GENERATE_E164_PHONE_NUMBER = 9,
  TRANSFORMER_SOURCE_GENERATE_FIRST_NAME = 10,
  TRANSFORMER_SOURCE_GENERATE_FLOAT64 = 11,
  TRANSFORMER_SOURCE_GENERATE_FULL_ADDRESS = 12,
  TRANSFORMER_SOURCE_GENERATE_FULL_NAME = 13,
  TRANSFORMER_SOURCE_GENERATE_GENDER = 14,
  TRANSFORMER_SOURCE_GENERATE_INT64_PHONE_NUMBER = 15,
  TRANSFORMER_SOURCE_GENERATE_INT64 = 16,
  TRANSFORMER_SOURCE_GENERATE_RANDOM_INT64 = 17,
  TRANSFORMER_SOURCE_GENERATE_LAST_NAME = 18,
  TRANSFORMER_SOURCE_GENERATE_SHA256HASH = 19,
  TRANSFORMER_SOURCE_GENERATE_SSN = 20,
  TRANSFORMER_SOURCE_GENERATE_STATE = 21,
  TRANSFORMER_SOURCE_GENERATE_STREET_ADDRESS = 22,
  TRANSFORMER_SOURCE_GENERATE_STRING_PHONE_NUMBER = 23,
  TRANSFORMER_SOURCE_GENERATE_STRING = 24,
  TRANSFORMER_SOURCE_GENERATE_RANDOM_STRING = 25,
  TRANSFORMER_SOURCE_GENERATE_UNIXTIMESTAMP = 26,
  TRANSFORMER_SOURCE_GENERATE_USERNAME = 27,
  TRANSFORMER_SOURCE_GENERATE_UTCTIMESTAMP = 28,
  TRANSFORMER_SOURCE_GENERATE_UUID = 29,
  TRANSFORMER_SOURCE_GENERATE_ZIPCODE = 30,
  TRANSFORMER_SOURCE_TRANSFORM_E164_PHONE_NUMBER = 31,
  TRANSFORMER_SOURCE_TRANSFORM_FIRST_NAME = 32,
  TRANSFORMER_SOURCE_TRANSFORM_FLOAT64 = 33,
  TRANSFORMER_SOURCE_TRANSFORM_FULL_NAME = 34,
  TRANSFORMER_SOURCE_TRANSFORM_INT64_PHONE_NUMBER = 35,
  TRANSFORMER_SOURCE_TRANSFORM_INT64 = 36,
  TRANSFORMER_SOURCE_TRANSFORM_LAST_NAME = 37,
  TRANSFORMER_SOURCE_TRANSFORM_PHONE_NUMBER = 38,
  TRANSFORMER_SOURCE_TRANSFORM_STRING = 39,
  TRANSFORMER_SOURCE_GENERATE_NULL = 40,
  TRANSFORMER_SOURCE_GENERATE_CATEGORICAL = 42,
  TRANSFORMER_SOURCE_TRANSFORM_CHARACTER_SCRAMBLE = 43,
  TRANSFORMER_SOURCE_USER_DEFINED = 44,
  TRANSFORMER_SOURCE_GENERATE_JAVASCRIPT = 45
}

export enum TransformerDataType {
  TRANSFORMER_DATA_TYPE_UNSPECIFIED = 0,
  TRANSFORMER_DATA_TYPE_STRING = 1,
  TRANSFORMER_DATA_TYPE_INT64 = 2,
  TRANSFORMER_DATA_TYPE_BOOLEAN = 3,
  TRANSFORMER_DATA_TYPE_FLOAT64 = 4,
  TRANSFORMER_DATA_TYPE_NULL = 5,
  TRANSFORMER_DATA_TYPE_ANY = 6,
  TRANSFORMER_DATA_TYPE_TIME = 7,
  TRANSFORMER_DATA_TYPE_UUID = 8
}

export enum SupportedJobType {
  SUPPORTED_JOB_TYPE_UNSPECIFIED = 0,
  SUPPORTED_JOB_TYPE_SYNC = 1,
  SUPPORTED_JOB_TYPE_GENERATE = 2
}

// export interface GetSystemTransformersResponse{
//   Array<Transformer>
// }

export interface Transformer{
    name:string,
    description:string,
    dataType:TransformerDataType,
    source:TransformerSource,
    config:any,
    dataTypes: TransformerDataType[]
    supportedJobTypes: SupportedJobType[]
}

export function useGetSystemTransformers(token: string | undefined): HookReply<Array<Transformer>> {
  return useAuthenticatedFetch(
    `/api/transformers/system`,
    !!token,
    token,
  )
}
